import { Rubik_Mono_One } from "next/font/google";
import "./globals.css";
import Header from './components/topNavigation/topNavigation';
import Footer from "./components/footer/footer";

const Rubik = Rubik_Mono_One({
  weight: "400",
  style: ["normal"],
  subsets: ["latin"],
  variable: "--font-highlight",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
           <body className={Rubik.variable}>
            <Header />
            {children}
            <Footer/>
            </body>
    </html>
  );
}
